[build]
  command = "npm run build" # Assuming your frontend build command is this
  publish = "frontend/dist" # Path to your frontend's build output
  functions = "netlify/functions" # Directory for Netlify functions

[functions]
  external_node_modules = ["express", "serverless-http", "cors"] # Add other backend dependencies if needed
  node_bundler = "esbuild"
  included_files = ["netlify/functions/items.json"]

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # 'api' should match your function file name (api.js)
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 